# Generated by Django 4.1.4 on 2023-03-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=50)),
                ('founder_avatar', models.ImageField(upload_to='')),
                ('founder_contact', models.IntegerField()),
                ('founder_linkedin', models.CharField(max_length=50)),
                ('founder_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
